# Generated by Django 2.1 on 2018-11-26 23:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quest_api', '0002_remove_team_count_fail_marker_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='time_take',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 26, 23, 21, 12, 70033, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='time_contact_marker',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 23, 21, 12, 60676, tzinfo=utc)),
        ),
    ]
