# Generated by Django 2.1 on 2018-11-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_api', '0002_marker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marker',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
