# Generated by Django 2.1 on 2018-11-26 23:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quest_api', '0003_auto_20181126_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='time_take',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='time_contact_marker',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
