# Generated by Django 2.1.3 on 2018-11-01 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest_api', '0003_auto_20181101_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='quest_api.Team'),
        ),
    ]
