# Generated by Django 2.1 on 2018-11-14 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest_api', '0004_marker_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='team_taken',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taken_markers', to='quest_api.Team'),
        ),
    ]
