# Generated by Django 2.1.3 on 2018-11-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_api', '0004_auto_20181101_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marker',
            old_name='isPublic',
            new_name='is_public',
        ),
        migrations.AddField(
            model_name='hint',
            name='read_teams',
            field=models.ManyToManyField(blank=True, null=True, to='quest_api.Team'),
        ),
    ]
