# Generated by Django 2.1 on 2018-11-27 00:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quest_api', '0004_auto_20181126_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='time_kill_zombie',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
